// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  dropdown: string;
  'dropdown__arrow-down': string;
  'dropdown__arrow-up': string;
  dropdown__error: string;
  dropdown__field: string;
  'dropdown__field--error': string;
  'dropdown__field--placeholder': string;
  dropdown__label: string;
  dropdown__options: string;
  'dropdown__options-wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
