// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'sort-panel': string;
  'sort-panel__arrow-down': string;
  'sort-panel__arrow-up': string;
  'sort-panel__option': string;
  'sort-panel__options': string;
  'sort-panel__title': string;
}
export const cssExports: CssExports;
export default cssExports;
