// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'scroll-btn': string;
  'scroll-btn--hide': string;
}
export const cssExports: CssExports;
export default cssExports;
