// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'banner': string;
  'banner__background': string;
  'banner__content': string;
  'banner__header': string;
  'banner__image': string;
  'banner__title': string;
}
export const cssExports: CssExports;
export default cssExports;
