// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close-menu-button__button': string;
  'close-menu-button__button--small': string;
  'close-menu-button__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
