// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alert-movie-modal__logo': string;
  'alert-movie-modal__message': string;
  'alert-movie-modal__title': string;
}
export const cssExports: CssExports;
export default cssExports;
