// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropdown-option': string;
  'dropdown-option__checkbox': string;
  'dropdown-option__checkbox--checked': string;
  'dropdown-option__checkbox-icon': string;
  'dropdown-option__content': string;
}
export const cssExports: CssExports;
export default cssExports;
