// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'movie': string;
  'movie__category': string;
  'movie__footer': string;
  'movie__image': string;
  'movie__image-wrapper': string;
  'movie__name': string;
  'movie__release': string;
  'movie__three-dots': string;
}
export const cssExports: CssExports;
export default cssExports;
