// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'delete-movie-modal__body': string;
  'delete-movie-modal__control': string;
}
export const cssExports: CssExports;
export default cssExports;
