// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'category-panel': string;
  'category-panel__item': string;
  'category-panel__item--active': string;
}
export const cssExports: CssExports;
export default cssExports;
