// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'movie-details': string;
  'movie-details__category': string;
  'movie-details__first-info-line': string;
  'movie-details__image': string;
  'movie-details__info': string;
  'movie-details__overview': string;
  'movie-details__rating': string;
  'movie-details__release-date': string;
  'movie-details__third-info-line': string;
  'movie-details__title': string;
}
export const cssExports: CssExports;
export default cssExports;
