// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  loader: string;
  loader__line: string;
  'loader__line--1': string;
  'loader__line--10': string;
  'loader__line--11': string;
  'loader__line--12': string;
  'loader__line--13': string;
  'loader__line--14': string;
  'loader__line--15': string;
  'loader__line--16': string;
  'loader__line--17': string;
  'loader__line--2': string;
  'loader__line--3': string;
  'loader__line--4': string;
  'loader__line--5': string;
  'loader__line--6': string;
  'loader__line--7': string;
  'loader__line--8': string;
  'loader__lines-wrapper': string;
  loader__text: string;
  'opacity-1': string;
}
export const cssExports: CssExports;
export default cssExports;
