// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'search': string;
  'search__button': string;
  'search__input': string;
  'search__title': string;
}
export const cssExports: CssExports;
export default cssExports;
