// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'movie-menu': string;
  'movie-menu__button': string;
}
export const cssExports: CssExports;
export default cssExports;
