// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'movie-board': string;
  'movie-board__count': string;
  'movie-board__count-number': string;
  'movie-board__header': string;
  'movie-board__header-underline': string;
  'movie-board__no-movie-found': string;
  'movie-board__show-more-button': string;
}
export const cssExports: CssExports;
export default cssExports;
