// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'button--big': string;
  'button--primary': string;
  'button--secondary': string;
  'button--small': string;
}
export const cssExports: CssExports;
export default cssExports;
