// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'modal-wrapper': string;
  'modal-wrapper__body': string;
  'modal-wrapper__content': string;
  'modal-wrapper__content-wrapper': string;
  'modal-wrapper__header': string;
}
export const cssExports: CssExports;
export default cssExports;
