// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error-page': string;
  'error-page__button': string;
  'error-page__error-number': string;
  'error-page__logo': string;
  'error-page__title': string;
}
export const cssExports: CssExports;
export default cssExports;
